apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grimoire-ingress
  namespace: grimoire
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: grimoire.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grimoire-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: grimoire-backend
                port:
                  number: 8080
