apiVersion: v1
kind: Secret
metadata:
  name: grimoire-secrets
  namespace: grimoire
type: Opaque
stringData:
  POSTGRES_DB: grimoiredb
  POSTGRES_USER: grimoire
  POSTGRES_PASSWORD: grimoire123
  SPRING_DATASOURCE_USERNAME: grimoire
  SPRING_DATASOURCE_PASSWORD: grimoire123
